### ISSUE TITLE
Implement the transversal CNOT for the surface code

### ISSUE THREAD

**Issue by MarcSerraPeralta** [MarcSerraPeralta/surface-sim#72]
TODO:

- [x] Aligning the rotated surface codes for the CNOTs between same data qubits
- [x] Add multi-logical-qubit functionality (#82)
- [x] Add logical qubit names to the logical qubit gate labels (#83)
- [x] Enforce unique qubit labelling, indices,... (#104)
- [x] Functionality to build layouts with different labelling, indices, ...
- [x] Being able to run parallel QEC cycles for two logical qubit patches after the CNOT (#100)
- [x] Computing `stab_gen_matrix` when involving more than one layout

**Comment by MarcSerraPeralta** [comment]
If the `Layout` represents a code, then the implementation of the logical CNOT will require two input layouts, one for the logical control and another for the logical target.

**Comment by MarcSerraPeralta** [comment]
One needs to add the property `logical_qubit_label(s)` in the layout to build the two-qubit gates. 
In the current implementation, the information about logical gates is stored in the layout using a single label for each gate. However, for the case of transversal CNOT, it is important to specify which logical qubit is the target and which the control because it the stabilizer matrix is different (and also one needs to specify the qubits in which the logical gate takes place). 
I propose having a list in the layout with all the labels for the different logical qubits and specifying the logical gate information as `"LOGGATENAME_involvedqubit1_involvedqubit2_..."`. This way there are no problems of conflicting gates as also the order of the involved qubits is important (e.g. for the CNOT, the first qubit represent the control and the second one the target).

**Comment by MarcSerraPeralta** [comment]
The PR #82 and #83 are related to the previous comment about specifying the involved logical qubits on the logical gate information as well as allowing to have multiple logical qubits in the same layout.

**Comment by MarcSerraPeralta** [comment]
Another issue when dealing with two different layouts is that if we want to run some QEC cycles in both of the patches at the same time it is not possible. The current way of doing it would be:

```
circuit = stim.Circuit()
circuit += qec_round(model, layout_1, detectors)
circuit += qec_round(model, layout_2, detectors)
```

This results in the "correct" noise channels but the ticks are not correct (we will have double the amount of ticks, for having two QECs). 

A possibility to solve this is to give a list of layouts to the `qec_round` and then, for each set of instructions between each `TICK`, do a for loop for all the layouts. 

Another option (that would also solve the issue about duplicated labels and indices) would be to have a `merge_layouts` function that merges two different layouts into a single one and ensures that everything is unique (and other things that I haven't realized yet...).

**Comment by MarcSerraPeralta** [comment]
I believe the `merge_layouts` function is the best approach (until now). The checks for this function would be:
- unique qubit labels
- unique qubit indices
- unique logical labels
- non-overlapping coordinates (if present)
- same interaction order

For the first three elements in the list, the `Layout` class will require some modifications. Currently, the indices cannot be specified as inputs and they are automatically built, starting from 0.

**Comment by MarcSerraPeralta** [comment]
I have realized that the computation of the `stab_gen_matrix` (which is the responsible for updating the stabilizer generators in the `Detectors`) is set to be done only for one layout, as it is implemented in `Layout.stab_gen_matrix. However, in the implementation of this transversal CNOT, the `stab_gen_matrix` involve stabilizers from two layouts, thus it cannot be computed from just a single one. 

One solution is to move this computation to the `Detectors` class and have a method that is `Detectors.update` and `Detectors.update_from_dict` (in which the dict is transformed to an xarray and then `Detectors.update` is called). This solves the issue (and possible other issues) because all the stabilizer generators that are being tracked are present in the `Detectors` object, and moreover this class is the one responsible for updating these generators.
